### ISSUE TITLE
Suggestion: copy note contents to clipboard

### ISSUE THREAD

**Issue by petebocken** [sballin/alfred-search-notes-app#11]
Copy the contents of the selected not to the clipboard. I use Apple Notes for all my code snippets and right now I use this workflow to search for the snippet, but then I have to manually copy the note contents to the clipboard. Being able to copy to the clipboard right in Alfred would be super great.

I was playing around with Evernote and the Evernote workflow and this appears to be able to do this. I'm assuming this is not apples and oranges, but just wanted to mention. https://www.alfredforum.com/topic/840-evernote-workflow-9-beta-4-alfred-4/

**Comment by sballin** [comment]
Feature added in release 2.0.0!
