### ISSUE TITLE
New Notes AppIcon.ics location

### ISSUE THREAD

**Issue by hadret** [sballin/alfred-search-notes-app#13]
In Catalina icon is now located under `/System`.

**Comment by sballin** [comment]
Thank you for the pull request. I want to make sure it's necessary before merging it, as it would break compatibility with older versions of macOS. The /Applications path still works for me, apparently it's "firmlinked" to /System/Applications. Is it different on your system?

**Comment by sballin** [comment]
Oh my bad, Notes.app is no longer in /Applications for me. The icon was still working properly for some reason. Will merge soon.
