### ISSUE TITLE
Does not work if xcode-select is not installed

### ISSUE THREAD

**Issue by ddzwigaj** [sballin/alfred-search-notes-app#17]
**Describe the bug**
I was scratching my head why this workflow does not work, debug log showed

Starting debug for 'Search Notes'

[2020-01-10 19:22:54][ERROR: input.scriptfilter] Code 1: xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.

I had to run two console commands, not sure if normal user would know how to do that tho
xcode-select --install
sudo xcode-select --reset

And now it works, i had Xcode installed but removed it, thats why

Not sure you can do about it, not sure if u can display alert that user dosnt have xcode-select installed

**Comment by sballin** [comment]
Thanks for documenting your process. I've updated the readme with instructions on installing the developer tools.
