### ISSUE TITLE
Ability to quick preview note with double shift like images and text files

### ISSUE THREAD

**Issue by ddzwigaj** [sballin/alfred-search-notes-app#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Pressing shift with note selected in alfred opens quick preview of it, just like images, text files

currently it displays this window 

<img width="1020" alt="Zrzut ekranu 2020-01-10 o 19 57 48" src="https://user-images.githubusercontent.com/26479276/72178689-b4ac3980-33e3-11ea-970e-1de6bd923f81.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by sballin** [comment]
I think you would need to make a custom Quick Look plugin for this. I don't have any experience with that, but I welcome contributions. In the meantime, if anyone knows how to disable this unhelpful preview for this particular script filter or the x-coredata:// UTI, do tell.

**Comment by sballin** [comment]
This output from the command `lsappinfo` might be relevant:

```
"Notes QuickLook Extension (Spotlight)" ASN:0x0-0x2d5ad58:
    bundleID="com.apple.Notes.QuickLookExtension"
    bundle path="/System/Applications/Notes.app/Contents/PlugIns/com.apple.Notes.QuickLookExtension.appex"
    executable path="/System/Applications/Notes.app/Contents/PlugIns/com.apple.Notes.QuickLookExtension.appex/Contents/MacOS/com.apple.Notes.QuickLookExtension"
    pid = 78452 type="BackgroundOnly" flavor=3 Version="1111.3" fileType="XPC!" Arch=x86_64 sandboxed
```
