### ISSUE TITLE
Notes folder and items are ignored

### ISSUE THREAD

**Issue by derek-arndt** [sballin/alfred-search-notes-app#24]
**Describe the bug**
When I search for notes in the default folder named "Notes" or try to open that folder It doesn't appear. I'm not sure if there's something different with my notes so the underlying AppleScript fails. Searching for notes in all other folders appear to work fine.

**To Reproduce**
1. Type 'n ' then a note name.
2. If it's in the 'Notes' folder it won't appear.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Alfred version: 4.0.9
 - Workflow version: 3.0.1

**Comment by sballin** [comment]
Thanks for the bug report. Can you try this version and let me know if it fixes the problem? [Search Notes.zip](https://github.com/sballin/alfred-search-notes-app/files/4765291/Search.Notes.zip)

**Comment by derek-arndt** [comment]
Yup, that fixed it!

Thanks,
Derek

**Comment by sballin** [comment]
Fixed in 3.0.2.
