### ISSUE TITLE
Make it work on OS X Catalina

### ISSUE THREAD

**Issue by lmuzquiz** [sballin/alfred-search-notes-app#25]
Does not work on Alfred 4 with OS X Catalina

**Comment by sballin** [comment]
Works for me! Can you provide more details?

**Comment by lmuzquiz** [comment]
YEs, hang on

**Comment by lmuzquiz** [comment]
Sorry it works, i didn't saw the first time the required setup:

The "search" binary needs to be manually authorized to run on your computer.

**Comment by sballin** [comment]
Nice, enjoy!
