### ISSUE TITLE
not support to search when my note has a table

### ISSUE THREAD

**Issue by lslz627** [sballin/alfred-search-notes-app#27]
**Describe the bug**
 can't find table content

**To Reproduce**

1、I have a note, the note contains a table  like this

name | tag | usage | mark | use help
-- | -- | -- | -- | --
jcmd | java | view jar startup argument | jcmd pid help | 

2、when i search by press `nb jcmd`, it show no result

**Desktop:**
 - OS: macOS 10.15 Catalina
 - Alfred version: Alfred 4
 - Workflow version: v3.0.2

**Additional context**

can't parse note format correctly when the note contains a table 

https://github.com/sballin/alfred-search-notes-app/blob/166f699956ae34a0c26a8ee613d4e33a1517c681/search/main.go#L205

I really appreciate your help，thank you!

**Comment by sballin** [comment]
Here is a new test version with table support, let me know if there are any issues! You can also grab the latest commit and compile if you prefer.

[Search Notes.alfredworkflow.zip](https://github.com/sballin/alfred-search-notes-app/files/4950855/Search.Notes.alfredworkflow.zip)

**Comment by lslz627** [comment]
> Here is a new test version with table support, let me know if there are any issues! You can also grab the latest commit and compile if you prefer.
> 
> [Search Notes.alfredworkflow.zip](https://github.com/sballin/alfred-search-notes-app/files/4950855/Search.Notes.alfredworkflow.zip)

it's cool, now it support to search text in a table, thank you very much!
