### ISSUE TITLE
Trying to authorize "search" fails with security warning

### ISSUE THREAD

**Issue by jasonoh** [sballin/alfred-search-notes-app#28]
**Describe the bug**
Installed the workflow and followed the instructions to manually authorize "search." However, when I do that, I get the following popup with no option to override the security warning:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/1554308/89044728-5cee0500-d318-11ea-9c85-d58c9e410e99.png">

A similar warning happens when I type in "n" to the alfred inteface, displaying the following popup instead with the additional option to "Move to Trash":
 
<img width="256" alt="image" src="https://user-images.githubusercontent.com/1554308/89045001-c5d57d00-d318-11ea-8bb7-577f2d9da887.png">

**To Reproduce**
1. install the workflow
2. try running "n" into the alfred search box
3. immediately get a error popup

1. install the workflow
2. try to authorize "search"
3. security warning popup displays

**Desktop (please complete the following information):**
 - OS: macOS 11 b3
 - Alfred version: 4.1
 - Workflow version: 3.1.0

**Additional context**
Typing ANY word that starts with "n" in the Alfred search box now immediately errors out as indicated above.

**Comment by sballin** [comment]
Are you doing right click -> open? Double clicking won't work. Or after it fails you can go into the "Security" preference pane and find the "allow" button near the bottom.

**Comment by jasonoh** [comment]
aha! there wasn't any prompt to authorize in the "Security -> Permission" for some reason... authorized it and it works! thanks for the speedy response and great workflow!
