### ISSUE TITLE
Copy notes:// URL doesn't work 

### ISSUE THREAD

**Issue by PicoNano** [sballin/alfred-search-notes-app#29]
**Using the copy note as URL feature throws error**

Here is the debug log output

```
[18:15:33.998] Search Notes[Script Filter] Queuing argument ''
[18:15:34.091] Search Notes[Script Filter] Script with argv '' finished
[18:15:34.094] Search Notes[Script Filter] {
    "items": [
        {
            "title": "Scratchpad",
            "subtitle": "Notes",
            "arg": "x-coredata://E56025F2-FC6A-42A7-8A73-EC73F575F9EF/ICNote/p3007?",
            "quicklookurl": null
        }

Deleted a bunch of these for privacy

    ]
}
[18:15:40.844] Search Notes[Script Filter] Processing complete
[18:15:40.845] Search Notes[Script Filter] Passing output 'x-coredata://E56025F2-FC6A-42A7-8A73-EC73F575F9EF/ICNote/p3007?' to Run NSAppleScript
[18:15:40.867] ERROR: Search Notes[Run NSAppleScript] {
    NSAppleScriptErrorAppName = Notes;
    NSAppleScriptErrorBriefMessage = "AppleEvent handler failed.";
    NSAppleScriptErrorMessage = "Notes got an error: AppleEvent handler failed.";
    NSAppleScriptErrorNumber = "-10000";
    NSAppleScriptErrorRange = "NSRange: {392, 4}";
}
[18:15:40.869] Search Notes[Run NSAppleScript] Processing complete
[18:15:40.869] Search Notes[Run NSAppleScript] Passing output '' to Run Script 
```

**To Reproduce**
1. Invoke Alfred
2. Type n (followed by a space)
3. ⌥ Return
4. Doesn't copy url to clipboard as expected, throws error. 

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Alfred version: 4.1
 - Workflow version: 3.1.0

**Comment by sballin** [comment]
Thanks for the report. I can't reproduce this... Can you verify that Alfred has permissions enabled in System Preferences > Security & Privacy > Privacy > Accessibility, Full Disk Access, Files and Folders, and Automation (for which there should be an "Alfred 4 > Notes" checkbox)?

If that doesn't fix it, what is your system language? Does this happen when you try to get the URL for a particular note, or any one of them?

**Comment by PicoNano** [comment]
Hi thanks for getting back to me. Alfred has permissions in all those places. My system language is English (Australia). And the problem occurs with all notes. I should mention the rest of the workflow functions and if I manually create a notes:// link, the Note Opener app works as expected.

**Comment by sballin** [comment]
Hmm, that's weird. You could try copying it into Script Editor.app and seeing where it goes wrong. If you need some guidance, I would start with trying just this to see if it works:

```applescript
use framework "Foundation"
use scripting additions -- fixes errors due to previous line
property NSString : a reference to current application's NSString
property NSCharacterSet : a reference to current application's NSCharacterSet

set q to "x-coredata://E56025F2-FC6A-42A7-8A73-EC73F575F9EF/ICNote/p3007?"
set q to text 1 thru ((offset of "?" in q) - 1) of q
```

then keep adding lines and see where the error happens.

**Comment by PicoNano** [comment]
<img width="694" alt="Screen Shot 2020-08-19 at 1 52 38 am" src="https://user-images.githubusercontent.com/4795315/90535911-bb433080-e1be-11ea-8aa1-04a7eac34cf7.png">
Seems that error crops up immediately :(
<img width="694" alt="Screen Shot 2020-08-19 at 1 53 23 am" src="https://user-images.githubusercontent.com/4795315/90535949-c5fdc580-e1be-11ea-86c0-48ce206d0b60.png">

**Comment by sballin** [comment]
Can you try restarting? And if that doesn't fix it, try unchecking and rechecking the permission checkboxes.

**Comment by PicoNano** [comment]
Im so sorry to report that neither has made a difference. Unfortunately for now I have to go to bed (its 2:33am here lol)

**Comment by sballin** [comment]
Oh, I think we encountered this issue before! Try changing the line to

```applescript
set noteName to name of note id q in default account
```

**Comment by PicoNano** [comment]
Hey that fixed it, thanks. It's so nice to have note linking functionality 💛
