### ISSUE TITLE
turn query into the body of a new note as a fallback when unable to search note

### ISSUE THREAD

**Issue by marcuskwan** [sballin/alfred-search-notes-app#30]
problem i'm having
hi sean - my problem is that id like to turn my query into a new note if the workflow is unable to find it - a body version of how a new note is created, when the workflow can't find the title in the title search function.
i.e. type "nb remember to buy bread" -> workflow realizes there is no "remember to buy bread" text, and creates a new note with the query being the body -> a new note with an empty heading with "remember to buy bread" as the body is created.
Right now I have it set up in apple note preferences that while searching/creating a new note title, the default text is the body, so when I want to create a new note I type "nt *insert new note text here*" 
Still a beginner at code so I can't read the workflow well, from opening the workflow in Alfred I see that "nb" command is connected to the third "creating a new note" task, but it doesn't seem to be working.

solution
have "create a new note with query" as a fallback option after pressing return, when no notes can be found with the query

alternatives
I googled other note workflows but they haven't been updated to work for alfred 4 or just don't work, really hope you can help!

**Comment by sballin** [comment]
This feature is now available in version 3.1.3!
