### ISSUE TITLE
No way to create a new note deterministically

### ISSUE THREAD

**Issue by babramczyk** [sballin/alfred-search-notes-app#32]
Since the only way to create a new note is to have no results, you're kind of out of luck if it matches _anything_.

For example, if I want to create a new note called "Bowling", but there's already a new called "Plans for Bowling", there's no way to do so currently with this workflow.

**Comment by sballin** [comment]
Added in version 3.4.0.

**Comment by babramczyk** [comment]
Awesome, appreciate the work, @sballin! 😀
