### ISSUE TITLE
Have an option to select which folder notes get created in

### ISSUE THREAD

**Issue by ghost** [sballin/alfred-search-notes-app#34]
It would be great if there was an option to select which folder a note was created in.  For example I have two folders and want all my new notes to be in the second 'inbox' folder so they are all together for me to review later on.  Currently each note gets saved to the first folder.

**Comment by kzssc** [comment]
Dear sender, 

Subject: Change of Email Domain

Starting from Friday, 3 January 2020, my personal email domain will gradually move to czhang.uk (from vpchris.com). Please save my new email address (same ***@***.*** (e.g., ***@***.***), and remove the current one from your system to avoid future disappointment.   Nevertheless this email has been forwarded, rest assured that you do not need to resend your message.   

Gracias.
 C.
