### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by mchmarny** [sballin/alfred-search-notes-app#37]
**To Reproduce**
Search notes on M1 silicon Mac 

**Info**
 - macOS version: 11.3
 - Alfred version: 4.3.4
 - Workflow version: v3.3.0
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events? Yes
 - What is the output of the [debug log](https://www.alfredapp.com/help/workflows/advanced/debugger/) when the error occurs? `Bad CPU type in executable`

**Additional context**
Rebuilding the excitable in workflow directory on M1 machine with 1.16 resolves this issue

**Proposed Implementation**
If you're on macOS Catalina with Alfred 4, download the latest version of the workflow for:
* Intel (x86)
* Apple (M1)

**Comment by sballin** [comment]
Thanks for bringing this to my attention, that's a big one! I decided to try creating a universal binary since the size wasn't too big to begin with. Since I don't have access to an M1 mac, could you tell me if the attached works on your system?

[Search Notes.alfredworkflow.zip](https://github.com/sballin/alfred-search-notes-app/files/6409895/Search.Notes.alfredworkflow.zip)

**Comment by tachim** [comment]
By the way, the latest version (as of 7 days ago) works flawlessly on my M1.

**Comment by sballin** [comment]
Do you mean the one linked in my previous comment on this issue? If not, it would be great if you could test that particular version, which I compiled as usual and didn't code sign. I read in some guides that code signing requirements are a little stronger with M1 binaries, so I'd appreciate if anyone with an M1 could let me know if it works with the same steps as described in the readme: https://github.com/sballin/alfred-search-notes-app#required-setup

**Comment by tachim** [comment]
I don't have the bandwidth to try another copy of it at the moment, but I can confirm it's v3.3.0:

![image](https://user-images.githubusercontent.com/11812/118028505-00445f80-b318-11eb-8d0e-6b144cc01236.png)

**Comment by sballin** [comment]
As of version 3.4.0, the binary in this workflow should work natively on M1 and Intel.
