### ISSUE TITLE
Question: how do you use the shortcut created by the app?

### ISSUE THREAD

**Issue by tachim** [sballin/alfred-search-notes-app#38]
E.g. given a shortcut like shortcuts://run-shortcut?name=NoteURL&input=1619999142, what app is needed to click to follow? It doesn't seem to have a native handler either on macOS or on iOS.

**Comment by sballin** [comment]
That's described here: https://github.com/sballin/alfred-search-notes-app#note-linking

The app to open them on macOS is included in the workflow you downloaded in [workflow root directory]/Open Notes URL/Open Notes URL.app. So when macOS asks what to use to open the link, you need to select Open Notes URL.app at that location.

**Comment by tachim** [comment]
Ah, I missed that. It works perfectly.
