### ISSUE TITLE
Stopped working after MacOS 11.4 upgrade

### ISSUE THREAD

**Issue by axhamre** [sballin/alfred-search-notes-app#39]
**To Reproduce**
1. I'm getting the error message described in "Required setup": https://github.com/sballin/alfred-search-notes-app#required-setup'
2. Step 3 in the instructions doesn't work, as the "Open Anyway" button doesn't appear.

**Info**
 - macOS version: 11.4
 - Alfred version: 4.0
 - Workflow version: 3.3.0
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events? Yes
 - What is the output of the [debug log](https://www.alfredapp.com/help/workflows/advanced/debugger/) when the error occurs?

```
panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
	github.com/sballin/alfred-search-notes-app/main.go:394
main.main()
	github.com/sballin/alfred-search-notes-app/main.go:407 +0x789
panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
	github.com/sballin/alfred-search-notes-app/main.go:394
main.main()
	github.com/sballin/alfred-search-notes-app/main.go:407 +0x789
panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
	github.com/sballin/alfred-search-notes-app/main.go:394
main.main()
	github.com/sballin/alfred-search-notes-app/main.go:407 +0x789
panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
	github.com/sballin/alfred-search-notes-app/main.go:394
main.main()
	github.com/sballin/alfred-search-notes-app/main.go:407 +0x789
panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
	github.com/sballin/alfred-search-notes-app/main.go:394
main.main()
	github.com/sballin/alfred-search-notes-app/main.go:407 +0x789
panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
	github.com/sballin/alfred-search-notes-app/main.go:394
main.main()
	github.com/sballin/alfred-search-notes-app/main.go:407 +0x789
panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
	github.com/sballin/alfred-search-notes-app/main.go:394
main.main()
	github.com/sballin/alfred-search-notes-app/main.go:407 +0x789
panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
	github.com/sballin/alfred-search-notes-app/main.go:394
main.main()
	github.com/sballin/alfred-search-notes-app/main.go:407 +0x789
```

**Additional context**

**Comment by sballin** [comment]
The popup message suggests the most common problem people have, which is with setup, regardless of the real error. I think your setup is fine, because the error is coming from a line inside the code.

Did you change the file permissions of the executable `search_notes`? It's inside a directory of the same name in the workflow directory which you can access by right-clicking on the workflow in Alfred and selecting "Open in Finder".

In your terminal, can you tell me the output of 

    stat -x ~/Library/Group\ Containers/group.com.apple.notes/NoteStore.sqlite

And also (after `cd`ing into the workflow directory)

    stat -x search_notes/search_notes

**Comment by gitrobert42** [comment]
I ran into the same problem after upgrading to 11.4. 

From the plugin directory, I ran the search I was trying to run from Alfred, namely `./search_notes title NI`. It brought back valid search results. 

`{
    "items": [
        {
            "title": "NI Hiring",
            "subtitle": "NI Hiring",
            "arg": "x-coredata://34D75F64-A28E-4E94-B9EA-A44B6E3F0EB5/ICNote/p19?NI",
            "quicklookurl": null
        },
...
`

So I don't think it is actually permissions issue.

**Comment by sballin** [comment]
You're welcome! And thanks for confirming this is a widespread issue. The latest version I've been using has some changes in the binary and it's been working for me on 11.4, so could either of you install the attached and let me know if it works when searching through Alfred?

[Search Notes.alfredworkflow.zip](https://github.com/sballin/alfred-search-notes-app/files/6593639/Search.Notes.alfredworkflow.zip)

**Comment by gitrobert42** [comment]
I tried it and still got the same error. Well, slightly different. The offset is different. (+0x644 (new) vs +0x789(old)).

The error for me is:
1. Open the Alfred bar with ⌘+space.
2. Type letter n.
3. Immediate error.

**Comment by gitrobert42** [comment]
Also, I can confirm that I can still successfully run the script from the command line. 

The perms are:
-rwxr-xr-x 1 myuser  staff  13478770 May 30 09:27 search_notes/search_notes

Unfortunately, I don't know where to find the  "database" referenced by the error log, so I can't look up the perms on it. Either way, it's strange since the script runs fine when run as a script from the command line.

**Comment by sballin** [comment]
The database is here: ~/Library/Group\ Containers/group.com.apple.notes/NoteStore.sqlite

Would be good to know your permissions on that too.

**Comment by gitrobert42** [comment]
```
$ ls -la ~/Library/Group\ Containers/group.com.apple.notes/NoteStore.sqlite
-rw-r--r--  1 myuser  staff  15757312 Jun  4 01:13 /Users/rr/Library/Group Containers/group.com.apple.notes/NoteStore.sqlite
```

**Comment by gitrobert42** [comment]
```
ls -la ~/Library/Group\ Containers/group.com.apple.notes/NoteStore.sqlite
-rw-r--r--  1 myuser  staff  15757312 Jun  4 01:13 /Users/myuser/Library/Group Containers/group.com.apple.notes/NoteStore.sqlite
```

**Comment by gitrobert42** [comment]
I am able to access that sqlite file with sqlite3 and read the tables.

**Comment by gitrobert42** [comment]
I compiled the project in Golang 1.16 for my M1 Mac, and Alfred still throws up this error (and only this error. not the others depicted in OP's link):
![image](https://user-images.githubusercontent.com/5825735/120785429-51cabd80-c557-11eb-8827-6bbce435b86d.png)

I tried replacing the search_notes binary with my own binary that simply writes "Hello World" to stderr. That binary runs fine.

**Comment by gitrobert42** [comment]
Some tweaking of your search_notes, and I extracted the long SELECT query. I verified I was able to run that query successfully in sqlite3. I also verified that NewLiteDB and NewNotesDB do not generate err values.

**Comment by gitrobert42** [comment]
Well, I finally figured it out. Alfred didn't have Full Disk Access checked in the Security & Privacy → Privacy pane. Once I check off Full Disk access it worked fine.

**Comment by sballin** [comment]
When you tested search_notes from the command line, did you have a search string? If not, the executable doesn’t really do anything. This is how to search:

./search_notes body "search string"

**Comment by sballin** [comment]
Ah, that makes sense! I will make this more explicit in the setup instructions. 

Still not sure why that would have changed during the upgrade to 11.4

**Comment by gitrobert42** [comment]
I'm not sure either. Maybe 11.4 tightened up the sandbox.

**Comment by axhamre** [comment]
> Well, I finally figured it out. Alfred didn't have Full Disk Access checked in the Security & Privacy → Privacy pane. Once I check off Full Disk access it worked fine.

This solved it for me as well, thank you!

And thank you @gitrobert42 for an amazing plugin.

**Comment by petemaunder91** [comment]
Alfred does have full disk access for me, however the issue still persists.
