### ISSUE TITLE
MacOS Monterey

### ISSUE THREAD

**Issue by Tigeredgar** [sballin/alfred-search-notes-app#41]
Most likely a bug in Monterey but the "search_notes" permission is not appearing on the Security Preferences to allow. Again, most likely a bug in MacOS but did want to bring it up.

**Comment by sballin** [comment]
In the workflow directory in Terminal, can you try doing `xattr -rd com.apple.quarantine search_notes` and see if that makes it work?

**Comment by Tigeredgar** [comment]
How do I find the workflow directory? I tried it on the Alfred app itself but did not work.

Warm Regards,
Edgar Salas

**Comment by Tigeredgar** [comment]
I was able to find it, ran it, succeeded but it’s still not working.

Will update you on beta 2

Warm Regards,
Edgar Salas

**Comment by sballin** [comment]
Thanks for trying that. I was able to get it working on the Monterey beta without trouble, so I'd be interested if you could show your debug log (click the bug icon in the top right corner of the workflow page and try running the workflow).

**Comment by sballin** [comment]
Can you show the contents of error_log.txt in the workflow directory? Also in System Preferences > Security and Privacy pane > Privacy tab, make sure that Alfred has full disk access.

**Comment by Tigeredgar** [comment]
Full Disk access fixed the issue! Thank you!

Warm Regards,
Edgar Salas

**Comment by sballin** [comment]
You're welcome!
