### ISSUE TITLE
Note linking

### ISSUE THREAD

**Issue by sballin** [sballin/alfred-search-notes-app#42]
It looks like there is a handy built-in way to link to notes.

### On macOS

`notes://showNote?identifier=A5E7652C-26A5-4E42-8393-F300D7E5C80B`

### On iOS

`mobilenotes://showNote?identifier=A5E7652C-26A5-4E42-8393-F300D7E5C80B`

The identifiers are the same across computers/phones and are stored in the Notes SQL database (column zidentifier in table ziccloudsyncingobject) and the content graph of the note on iOS. 

This is almost perfect except that it appears you would need to have one of each type of URL in order to have the link functionality on both platforms, as the mobilenotes:// link doesn't work on macOS and vice-versa.

@temochka any thoughts? As you predicted there is now a Shortcuts app in macOS Monterey.

**Comment by temochka** [comment]
Last time I looked into this, there was no automatic way to grab the note id from a shortcut on iOS (could only copy/paste it from the content graph), has this changed recently? My take is that until there’s a unified URL scheme across platforms and a way to easily generate URLs, the shortcuts solution will remain relevant (at least for me).

**Comment by sballin** [comment]
Yeah, those drawbacks are still there unfortunately. I guess the options if we used this scheme are 1. have the macOS app handle mobilenotes:// URLs by simply opening the equivalent notes:// URL, while the mobilenotes:// links work out of the box on iOS, or 2. have the Alfred workflow create both a mobilenotes:// link and a notes:// link side by side, and the user has to click the right one depending on the platform they're on. Both of these seem a little icky to me, but I am drawn by the lack of any code required...

On the one hand, I figure that people aren't creating a ton of links between notes on iOS, so maybe it's ok that that's a little awkward. On the other hand, I don't want to keep changing up the note linking format on people. There's also no telling how long it will take for Apple to unify these URL schemes—I don't really see why they would be motivated to.
