### ISSUE TITLE
Alfred Search Notes Worflow Error

### ISSUE THREAD

**Issue by petemaunder91** [sballin/alfred-search-notes-app#43]
**To Reproduce**
1. Type 'n' into Alfred search bar

**Info**
 - macOS version: BigSure 11.4
 - CPU: Intel or Apple (M1)? Intel
 - Alfred version: 4.3.4
 - Workflow version: 3.3.0
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events? 
 Yes, except don't have the option to turn on "Automation > Alfred 4 > System Events"

**Additional context**
After typing "n" into Alfred I get the below error. It had been working perfectly up until about a week or so ago.

![image](https://user-images.githubusercontent.com/86329260/123009843-da26da80-d400-11eb-94dd-0445a3ebee97.png)

**Comment by sballin** [comment]
What shows up in the error log and debug log?

**Comment by petemaunder91** [comment]
Error Log:

/Users/pete/Library/Caches/com.runningwithcrayons.Alfred/Workflow
Scripts/8BF1766F-EC94-4CF2-BD10-53D0CDD08883: line 2:
/Users/pete/Library/Application
Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9CB1BE6-EF07-4698-A2E1-A17A9CEA329E/search_notes/search_notes:
No such file or directory
/Users/pete/Library/Caches/com.runningwithcrayons.Alfred/Workflow
Scripts/CF857E17-6DE2-4E5B-A7E0-935A2F1087D6: line 2:
/Users/pete/Library/Application
Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9CB1BE6-EF07-4698-A2E1-A17A9CEA329E/search_notes/search_notes:
No such file or directory
/Users/pete/Library/Caches/com.runningwithcrayons.Alfred/Workflow
Scripts/1D94E1A9-7B59-4356-9CDD-A023F1D41B08: line 2:
/Users/pete/Library/Application
Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9CB1BE6-EF07-4698-A2E1-A17A9CEA329E/search_notes/search_notes:
No such file or directory
/Users/pete/Library/Caches/com.runningwithcrayons.Alfred/Workflow
Scripts/23DFE0BE-7544-4241-A048-04361FBDBD44: line 2:
/Users/pete/Library/Application
Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9CB1BE6-EF07-4698-A2E1-A17A9CEA329E/search_notes/search_notes:
No such file or directory
/Users/pete/Library/Caches/com.runningwithcrayons.Alfred/Workflow
Scripts/B2C738CC-288C-4B91-A95D-6202B566B3F0: line 2:
/Users/pete/Library/Application
Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9CB1BE6-EF07-4698-A2E1-A17A9CEA329E/search_notes/search_notes:
No such file or directory
/Users/pete/Library/Caches/com.runningwithcrayons.Alfred/Workflow
Scripts/D2C8BB39-8F0E-44A1-953E-34BF830A2DEC: line 2:
/Users/pete/Library/Application
Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9CB1BE6-EF07-4698-A2E1-A17A9CEA329E/search_notes/search_notes:
No such file or directory
/Users/pete/Library/Caches/com.runningwithcrayons.Alfred/Workflow
Scripts/57C59F42-6109-4FAD-8FF1-1481E3F7B9FF: line 2:
/Users/pete/Library/Application
Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9CB1BE6-EF07-4698-A2E1-A17A9CEA329E/search_notes/search_notes:
No such file or directory
/Users/pete/Library/Caches/com.runningwithcrayons.Alfred/Workflow
Scripts/D88AAB54-48EC-4AC1-A943-39810BE1398D: line 2:
/Users/pete/Library/Application
Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9CB1BE6-EF07-4698-A2E1-A17A9CEA329E/search_notes/search_notes:
No such file or directory

I'm not sure how to get the debug log.


Thanks,
Pete

**Comment by sballin** [comment]
Maybe you moved the search_notes binary to the trash? It’s one of the macOS dialog buttons when you first try to run the workflow, but you don’t want to press it. See the “Required setup” part of the readme. The easiest way to fix this is probably to reinstall the workflow.

**Comment by merchako** [comment]
I'm also having this problem, even after reinstalling the workflow. Sometimes I get the option to allow the app in the Security and Privacy preference pane, and sometimes I don't. Even when I get the option and allow it, I still get this error every time I start an Alfred query with "n".

**Comment by sballin** [comment]
Here are some related issues: https://github.com/sballin/alfred-search-notes-app/issues/31#issuecomment-738567854 and https://github.com/sballin/alfred-search-notes-app/issues/39#issuecomment-855355859.

You can also try this beta version (will still say version number 3.3.0): [Search Notes.alfredworkflow.zip](https://github.com/sballin/alfred-search-notes-app/files/6704697/Search.Notes.alfredworkflow.zip)

**Comment by merchako** [comment]
#39 (comment) solved it for me. It seems Alfred lost disk access or didn't get it, and I didn't realize it. Thank you.

**Comment by sballin** [comment]
@petemaunder91 what kind of accounts are you using to store your notes (iCloud/on my mac/email)?

You could try moving this directory to the trash: /Users/pete/Library/Caches/com.runningwithcrayons.Alfred/Workflow
Scripts/8BF1766F-EC94-4CF2-BD10-53D0CDD08883

**Comment by petemaunder91** [comment]
Stored on iCloud.

I have tried uninstalling and reinstalling the workflow.
The weird thing is that it is still working on the Macbook.

I went to this directory:
/Users/pete/Library/Caches/com.runningwithcrayons.Alfred/
But the only folders within that were
applescript
extensions_tmp
updates
workflow data
(all of which were empty)

Thanks,
Pete

**Comment by sballin** [comment]
First I would suggest upgrading to version 3.4.0 that was just released, as the error messages are a little more helpful.

If the error is still happening, can you verify that this file exists: /Users/pete/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9CB1BE6-EF07-4698-A2E1-A17A9CEA329E/search_notes/search_notes

and if it is, you could try these commands in your terminal:

```
cd "/Users/pete/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9CB1BE6-EF07-4698-A2E1-A17A9CEA329E/search_notes"

./search_notes title something
