### ISSUE TITLE
Functionality to create new note isn't working

### ISSUE THREAD

**Issue by binarysprocket** [sballin/alfred-search-notes-app#45]
The creating a new note functionality isn't working. If I type 'n here is a new note' it just tries to Google search that text. In other words, the Alfred-search-notes-app workflow exits and alfred defaults to google search. It finds my notes with no problem but creating a new note is not working. Any ideas why? Thanks in advance. 

Fill out this information if it's not already included in the error text.

 - macOS version: 11.4
 - CPU: Intel or Apple (M1)? M1
 - Alfred version: 4.3.4
 - Workflow version: 3.4.1
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events?
 - What type of account are your notes stored in (iCloud/On My Mac/Email)? iCloud
 - If the workflow can't manage to show a list of your notes, verify that the search_notes executable file is present by right-clicking the "Search Notes" workflow in the workflow list of Alfred Preferences, choosing "Open in Finder" and opening the search_notes folder. Is there a file of the same name inside that folder?
 - If no error notification appears automatically, what is the output of the [debug log](https://www.alfredapp.com/help/workflows/advanced/debugger/) when you reproduce the problem?

**Comment by binarysprocket** [comment]
I'm an idiot and did not see the command needs to be 'nc' not just 'n'. Closing this issue.

**Comment by sballin** [comment]
Also "n" can fall back on creating a note when none are found. This option is controlled via the workflow environment variables ("[x]" button in top right corner of the workflow connection diagram). It sounds like you also have some of the Alfred default web search fallbacks, which you can disable in the general Alfred settings if you choose.

**Comment by binarysprocket** [comment]
Ahh gotcha. Thanks, Sean - much appreciated!
