### ISSUE TITLE
Feature: create note if not exists

### ISSUE THREAD

**Issue by hazcod** [sballin/alfred-search-notes-app#46]
Hi! Would be nice if `n <filter>`would create a new Note with title `<filter>` if it wasn't found in Alfred.
Currently it exits the search-notes workflow.

![image](https://user-images.githubusercontent.com/5222512/124425641-2232ef00-dd69-11eb-8dc4-78dc7706ad86.png)

**Comment by sballin** [comment]
See https://github.com/sballin/alfred-search-notes-app/issues/45

**Comment by hazcod** [comment]
Gotcha! Thanks!
