### ISSUE TITLE
search_notes error panic: unable to open database file: operation not permitted

### ISSUE THREAD

**Issue by kevinebaugh** [sballin/alfred-search-notes-app#49]
**To Reproduce**

Steps/context to reproduce the behavior:

1. Search for a note
2. Error below

**Error text**

```
Please copy this entire text if submitting an error report. You may need to scroll.

panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
github.com/sballin/alfred-search-notes-app/main.go:502
main.main()
github.com/sballin/alfred-search-notes-app/main.go:515 +0x654

macOS: 11.5.1
Alfred: 4.5.1
Workflow: 3.4.1
CPU: arm64e
Binary xattrs: com.dropbox.attrs
Notes DB xattrs: com.apple.quarantine
Binary info: 0755 501/ke 20/staff
Notes DB info: 0644 501/ke 20/staff
Query: title ''
Accounts: (-1743) Not authorized to send Apple events to Notes.
```

**Info**

Fill out this information if it's not already included in the error text.

 - macOS version: 11.5.1
 - CPU: M1
 - Alfred version: 4.5.1 [1256]
 - Workflow version: 3.5.0, 3.4.1
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events? 

    Looks like System Events might be the culprit: 
    <img width="780" alt="Screen Shot 2021-08-10 at 12 52 33 PM" src="https://user-images.githubusercontent.com/3092522/128901262-e661473f-0142-4e64-84d9-0ddddc7d227c.png">

 - What type of account are your notes stored in (iCloud/On My Mac/Email)? iCloud
 - If the workflow can't manage to show a list of your notes, verify that the search_notes executable file is present by right-clicking the "Search Notes" workflow in the workflow list of Alfred Preferences, choosing "Open in Finder" and opening the search_notes folder. Is there a file of the same name inside that folder? Yes
 - If no error notification appears automatically, what is the output of the [debug log](https://www.alfredapp.com/help/workflows/advanced/debugger/) when you reproduce the problem?

**Comment by sballin** [comment]
Glad it worked out!
