### ISSUE TITLE
v3.4.0+ not work on 10.14

### ISSUE THREAD

**Issue by learn2reid** [sballin/alfred-search-notes-app#50]
**To Reproduce**

Steps/context to reproduce the behavior:

1. Search for a note
2. ...

**Error text**

Copy and paste the full error text from any error messages. Screenshots can also help but may not show the full text.

**Info**

Fill out this information if it's not already included in the error text.

 - macOS version:
 - CPU: Intel or Apple (M1)?
 - Alfred version:
 - Workflow version:
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events?
 - What type of account are your notes stored in (iCloud/On My Mac/Email)?
 - If the workflow can't manage to show a list of your notes, verify that the search_notes executable file is present by right-clicking the "Search Notes" workflow in the workflow list of Alfred Preferences, choosing "Open in Finder" and opening the search_notes folder. Is there a file of the same name inside that folder?
 - If no error notification appears automatically, what is the output of the [debug log](https://www.alfredapp.com/help/workflows/advanced/debugger/) when you reproduce the problem?

**Comment by sballin** [comment]
Should be fixed in version 3.5.1
