### ISSUE TITLE
Error creating new note from different space than main window

### ISSUE THREAD

**Issue by Staudi** [sballin/alfred-search-notes-app#51]
**To Reproduce**

Steps/context to reproduce the behavior:

1. Search for a note that doesn't exists
2. Press enter to create new note
3. Workflow switches to space with notes main window and creates the note
4. When you go back to space from which you activated workflow there is Alfred error window with following error

**Error text**

`-1719: System Events got an error: Can’t get window 1 of process "Notes". Invalid index.`

<img width="532" alt="Screenshot 2021-09-26 at 12 47 13" src="https://user-images.githubusercontent.com/713654/134804841-02e4b242-9cee-49a9-83e1-6451a89293a6.png">

**Info**

Fill out this information if it's not already included in the error text.

 - macOS version: 10.15.7
 - CPU: Intel 
 - Alfred version: 4.5.1 [1256]
 - Workflow version: 3.5.1
 - Full disk access: Yes
 - Icloud
 - Nothing in debug log

**Comment by sballin** [comment]
Should be fixed in version 3.5.2
