### ISSUE TITLE
Problem when creating a new note w/ "nc" command

### ISSUE THREAD

**Issue by DD-09** [sballin/alfred-search-notes-app#54]
**To Reproduce**

Steps/context to reproduce the behavior:

1. Type "nc" in Alfred Search bard
2. Type new text and press enter

**Error text**

<img width="246" alt="Screen Shot 2021-11-17 at 10 07 12 AM" src="https://user-images.githubusercontent.com/94508692/142226369-78be16db-a94e-422e-a73a-280d6dfd49ca.png">

"-1719: System Events got an error: Can’t get group 1 of splitter group 1 of splitter group 1 of window 1 of process "Notes". Invalid index."

**Info**

Fill out this information if it's not already included in the error text.

 - macOS version: Monterey
 - CPU: Apple (M1)
 - Alfred version: 4.6
 - Workflow version: The Latest? Yesterday, I downloaded it directly here and followed with the update prompt that popped up in Alfred.
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events? Yes
 - What type of account are your notes stored in (iCloud/On My Mac/Email)? iCloud
 - If the workflow can't manage to show a list of your notes, verify that the search_notes executable file is present by right-clicking the "Search Notes" workflow in the workflow list of Alfred Preferences, choosing "Open in Finder" and opening the search_notes folder. Is there a file of the same name inside that folder? Yes
 - If no error notification appears automatically, what is the output of the [debug log](https://www.alfredapp.com/help/workflows/advanced/debugger/) when you reproduce the problem? Unsure

**Comment by sballin** [comment]
Are you viewing notes in Gallery mode? This workflow only supports List mode (Menubar -> View -> as List)

**Comment by DD-09** [comment]
Oh snap, that fixed it. Thanks!
