### ISSUE TITLE
Python2 reappeared

### ISSUE THREAD

**Issue by maxim** [sballin/alfred-search-notes-app#55]
After merging [python3 PR](https://github.com/sballin/alfred-search-notes-app/pull/16), looks like there are now 2 places where python2 reappeared:

1. [update.py](https://github.com/sballin/alfred-search-notes-app/blob/272ed164597e0954357ed1d2d1fbddf186f7e1f6/update.py#L1)
2. [info.plist](https://github.com/sballin/alfred-search-notes-app/blob/1c0f15af39ae7e6a70428c1dfaeaa58b07e0d382/info.plist#L767)

This triggered the macOS "Software needs to be updated" dialog for me, where "learn more" said "python2 is on its way out".

**Comment by sballin** [comment]
I haven't seen that dialog yet... I think python 3 still requires developer tools to be installed on mac so I don't really want to make the update script use it. Maybe I'll have to rewrite it in bash...

**Comment by sballin** [comment]
Are you on one of the developer previews?

**Comment by maxim** [comment]
Hm, looks like python3 PR was merged, do you think it should be reverted? I'm on Monterey 12.0.1.

**Comment by sballin** [comment]
The files in that PR no longer exist, their functionality is in a Go binary now. The only remaining python 2 file is the update.py script. Until python 3 is included by default in macos (without having to install dev tools) I don't really want to make scripts use it. So unless this warning appears constantly, I don't think I want to change it right now. Long-term I guess I'll change the update script to bash/applescript.

**Comment by maxim** [comment]
Ahh, gotcha. That makes perfect sense. It doesn't appear constantly, so long term plan sounds good. 👍🏻

**Comment by dsully** [comment]
This is appearing constantly for me now on Monterey 12.1 RC2

**Comment by pctony** [comment]
This is now appearing in the latest MacOS production release: 

MacOS 12.1 (21C52)
<img width="1262" alt="Screen Shot 2022-01-20 at 5 31 32 PM" src="https://user-images.githubusercontent.com/78299/150449286-454eae70-b34c-40b0-97dc-cbc8eee5dc5f.png">

**Comment by pctony** [comment]
<img width="1061" alt="Screen Shot 2022-01-20 at 5 33 04 PM" src="https://user-images.githubusercontent.com/78299/150449427-d996245e-d3db-4c75-83c9-e9d04da35087.png">

**Comment by pctony** [comment]
This was triggered when creating a new note; and is reproducible.

**Comment by pctony** [comment]
I can also confirm that python3 is not shipping in the OS as-is.  
```

╰─❯ ls -lah /usr/bin/python*
lrwxr-xr-x  1 root  wheel    75B Dec  7 15:39 /usr/bin/python@ -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x  1 root  wheel    82B Dec  7 15:39 /usr/bin/python-config@ -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
lrwxr-xr-x  1 root  wheel    75B Dec  7 15:39 /usr/bin/python2@ -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x  1 root  wheel    75B Dec  7 15:39 /usr/bin/python2.7@ -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x  1 root  wheel    82B Dec  7 15:39 /usr/bin/python2.7-config@ -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
-rwxr-xr-x  1 root  wheel   163K Dec  7 15:39 /usr/bin/python3*
lrwxr-xr-x  1 root  wheel    76B Dec  7 15:39 /usr/bin/pythonw@ -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
lrwxr-xr-x  1 root  wheel    76B Dec  7 15:39 /usr/bin/pythonw2.7@ -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7


╰─❯ cd ../../System/Library/Frameworks/Python.framework/Versions/
╭─   /System/Library/Frameworks/Python.framework/Versions ··································································································································································································· at  17:36:45
╰─❯ ls
2.3@     2.5@     2.6@     2.7/     Current@


```

**Comment by sballin** [comment]
Thanks for the info. Looks like it's time to translate the update script from python to bash.

**Comment by sballin** [comment]
The latest version now uses OneUpdater, so the project is finally free of python 2: https://github.com/sballin/alfred-search-notes-app/releases/download/3.6/Search.Notes.alfredworkflow
