### ISSUE TITLE
Could `n <title>` open a note in its own window?

### ISSUE THREAD

**Issue by pjvandehaar** [sballin/alfred-search-notes-app#56]
I prefer to have notes open in their own window.  Normally, I just double-click the note in the notes list to get that.  That saves screen space and lets me open other notes at the same time.

Could this workflow open the note in its own window, instead of in the main notes window?

Maybe there's an extra parameter to `notes://showNote` for this?  But I can't find any references to that URL on the internet, except to this repository.

**Comment by sballin** [comment]
This has been suggested in the past, but I don't know how to do it without excessive GUI scripting that would emulate enter/double-click on the name of the note in the sidebar. 

The notes://showNote business is not well documented at all, so I don't know how to use it for anything beyond what I'm currently doing. I tried looking in the Notes.app binary once for strings related to it and came up empty, though I'm no expert in that sort of thing so it might be worth another try.

If there is a non-GUI applescript way to do it, it's not documented either...

**Comment by pjvandehaar** [comment]
Well, if it’s not possible, feel free to close this issue.  That kind of GUI-clicking AppleScript is so brittle that it’s not worth trying.
