### ISSUE TITLE
Cannot open a note

### ISSUE THREAD

**Issue by Missionary2112** [sballin/alfred-search-notes-app#57]
**To Reproduce**

Steps/context to reproduce the behavior:

1. Open Apple Note in Gallery View
2. Go inside any note from the Gallery View
3. Search for a note: n ... (different from the current note)
4. Hit "return" to enter the note
5. Nothing happens

**Error text**

There is no error text. It just doesn't do anything.

**Info**

Fill out this information if it's not already included in the error text.

 - macOS version: macOS Monterey Version 12.2
 - CPU: Intel
 - Alfred version: 4.6.2
 - Workflow version: v3.5.2
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events?
 - What type of account are your notes stored in (iCloud/On My Mac/Email)? Gmail

**Comment by pressdarling** [comment]
Also getting this on Alfred 5. No errors, but it freezes up Alfred completely.

**Comment by sballin** [comment]
Please try disabling and re-enabling all permissions and see if that fixes it: https://github.com/sballin/alfred-search-notes-app#required-permissions

If it's still happening, can you try running it with the debug log open and let me know what messages appear? https://www.alfredapp.com/help/workflows/advanced/debugger/

**Comment by sballin** [comment]
Ah, the first post in this issue says their notes are stored in Gmail... that's unfortunately not supported by this workflow. @pressdarling are you also using Gmail to store your notes?

**Comment by pressdarling** [comment]
@sballin Nope - and funnily enough, it's working just fine on my other Mac. Seems @Missionary2112 has a different issue, I'll open one of my own after those steps if I encounter the issue again.

**Comment by Missionary2112** [comment]
Yeah sometimes it works sometimes it doesn't, especially the newly created notes. It's like rolling a dice whether you get lucky and the note is opened. 

https://user-images.githubusercontent.com/98799613/188368880-84d14ce9-e430-4d2c-8985-0c3257554986.mp4

**Comment by sballin** [comment]
Ah, you are doing View > as Gallery but this workflow only supports View > as List

**Comment by Missionary2112** [comment]
That's what I'm saying and that's what this post is about :)) Anyway, thank you for your insight.

**Comment by sballin** [comment]
Ah, sorry I glossed over that in your report. I would recommend putting it in the title.
