### ISSUE TITLE
search_notes error panic: no such column: zaccount4

### ISSUE THREAD

**Issue by sonu787** [sballin/alfred-search-notes-app#58]
Please copy this entire text if submitting an error report. You may need to scroll.

panic: no such column: zaccount4

goroutine 1 [running]:
main.PanicOnErr(...)
	github.com/sballin/alfred-search-notes-app/main.go:461
main.main()
	github.com/sballin/alfred-search-notes-app/main.go:474 +0x7f3

macOS: 10.13.6
Alfred: 4.6.3
Workflow: 3.5.2
CPU: i486
Binary xattrs: 
Notes DB xattrs: com.apple.quarantine
Binary info: 0755 501/harvinder 20/staff
Notes DB info: 0644 501/harvinder 20/staff
Query: folder ''
Accounts: iCloud

**Comment by sballin** [comment]
Looks like you’re on an older version of macOS. Installing an older version of the workflow is probably the easiest way to fix this.

**Comment by sonu787** [comment]
thanks. could you please guide as to how can I download the older version? thanks

**Comment by sballin** [comment]
They're here: https://github.com/sballin/alfred-search-notes-app/releases

I would try [3.3.0](https://github.com/sballin/alfred-search-notes-app/releases/download/3.3.0/Search.Notes.alfredworkflow), if that doesn't work then [3.1.3](https://github.com/sballin/alfred-search-notes-app/releases/download/3.1.3/Search.Notes.alfredworkflow), and if that doesn't work [3.0.2](https://github.com/sballin/alfred-search-notes-app/releases/download/3.0.2/Search.Notes.alfredworkflow).

**Comment by fcocchiano** [comment]
Hi there, in my case i got the same error message as @sonu787 and i am running the latest version of macOS. Should i also try installing the older version of the workflow? Please see below and thanks.

panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
github.com/sballin/alfred-search-notes-app/main.go:461
main.main()
github.com/sballin/alfred-search-notes-app/main.go:474 +0x654

macOS: 12.2.1
Alfred: 4.6.3
Workflow: 3.5.2
CPU: arm64e
Binary xattrs: com.dropbox.attrs
Notes DB xattrs: 
Binary info: 0755 501/fabmacmini 20/staff
Notes DB info: 0644 501/fabmacmini 20/staff
Query: title ''
Accounts: FAB, 😎FAB

**Comment by sballin** [comment]
I think that error is more likely to be fixed by disabling and re-enabling the required permissions: https://github.com/sballin/alfred-search-notes-app#required-permissions

**Comment by fcocchiano** [comment]
Thanks for the quick reply...it worked.
