### ISSUE TITLE
Search suggestion

### ISSUE THREAD

**Issue by Schvifty** [sballin/alfred-search-notes-app#6]
Hi,

Thanks for this workflow, it works great.
I have a "minor" suggestion when searching for notes which I noticed recently.

When you search with "n"-hotkey and then start typing the keyword, it switches from the workflow to default search when there is no match.
Would it be possible to change the output to something like "No results" instead?

Here is an example of what I mean when I search for a note with title "Workflow":
![screen shot 2019-01-17 at 07 24 35](https://user-images.githubusercontent.com/18008933/51299489-f7ce0980-1a28-11e9-916c-15fbe8b4d5c9.png)
This one is found which is great.

If I add the next letter in the keyword it switches from the Notes workflow to default Alfred search:
![screen shot 2019-01-17 at 07 25 51](https://user-images.githubusercontent.com/18008933/51299540-264be480-1a29-11e9-91cd-ce6cfe2ca120.png)

It would feel better if Alfred stayed in "Notes search mode" and gave me a result instead even if there are no matches, for example just outputting "No note found" or something like that. At the moment Alfred doesn't seem to care about the "n"-hotkey when there is no match and switches to default search.

Keep up the good work!

**Comment by sballin** [comment]
I'm glad the workflow is useful to you. Unfortunately it looks like this feature can't be implemented right now: https://www.alfredforum.com/topic/9695-fallback-action-when-script-filter-has-no-results/

I want to keep the "Alfred filters results" option for good performance, but if you want you can disable it, implement some filter in Python, and check the length of the `items` object in `searchNotes.py`, putting your error message if it's 0. 

If you find that it's possible to do what you want without disabling the Alfred filtering, feel free to reopen the issue.
