### ISSUE TITLE
can not create note

### ISSUE THREAD

**Issue by TwoAndOne** [sballin/alfred-search-notes-app#61]
**To Reproduce**

Steps/context to reproduce the behavior:

1. Create a note using the NC command
2. Then the following pop-up window appears

**Error text**

Copy and paste the full error text from any error messages. Screenshots can also help but may not show the full text.
<img width="320" alt="image" src="https://user-images.githubusercontent.com/44161851/180362089-6e7f19b6-4b0b-46b6-b3b1-b4ac3a3250fd.png">

**Info**

Fill out this information if it's not already included in the error text.

 - macOS version:12.3
 - CPU: Intel or Apple (M1)? M1
 - Alfred version:4.6.1
 - Workflow version:latest master
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events?
 - What type of account are your notes stored in (iCloud/On My Mac/Email)?
     icloud
 - If the workflow can't manage to show a list of your notes, verify that the search_notes executable file is present by right-clicking the "Search Notes" workflow in the workflow list of Alfred Preferences, choosing "Open in Finder" and opening the search_notes folder. Is there a file of the same name inside that folder?
 - If no error notification appears automatically, what is the output of the [debug log](https://www.alfredapp.com/help/workflows/advanced/debugger/) when you reproduce the problem?

**Comment by sballin** [comment]
You could try disabling and re-enabling the permissions: https://github.com/sballin/alfred-search-notes-app#required-permissions
