### ISSUE TITLE
Unable to Search Notes in Alfred 5

### ISSUE THREAD

**Issue by proxymetre1** [sballin/alfred-search-notes-app#62]
**To Reproduce**

Workflow is unable to work with Alfred 5, and it produces the following error

<img width="401" alt="2022-09-19 at 00 44 24@2x" src="https://user-images.githubusercontent.com/113851181/190918631-0f5c655e-a2d7-489e-93a0-79d334974dbd.png">

**Comment by sballin** [comment]
Have you tried disabling and re-enabling the permissions? https://github.com/sballin/alfred-search-notes-app#required-permissions

**Comment by proxymetre1** [comment]
he sballin, yea thanks! disabling and re-enabling permissions does the trick! thank you for the solution.
I've upgraded from Alfred 4, future user may have to take note to do this step indeed.

**Comment by m-cat** [comment]
I had this same issue and re-enabling permissions didn't work, nor did restarting Alfred or my computer. **I ended up having to re-install the workflow and then it worked.**
