### ISSUE TITLE
Search note doesn't work on MacOS Ventura

### ISSUE THREAD

**Issue by badyqb** [sballin/alfred-search-notes-app#63]
The search doesn't show any result in MacOS Ventura

**Comment by sballin** [comment]
Have you tried disabling and re-enabling all the permissions? https://github.com/sballin/alfred-search-notes-app#required-permissions

**Comment by florianlionel** [comment]
Had the same issue (on Alfred 5 and Ventura) and after fiddling around for a while deleting, reinstalling, permission resetting, etc. I quit Alfred (in Alfred's General Settings), relaunched it and it worked. Maybe it's worth a shot.

**Comment by badyqb** [comment]
@florianlionel I tried to re-install Alfred and redo the permissions, still doesn't work out for me.

**Comment by badyqb** [comment]
The lastest version solves this issue. Thanks for the update! ✨
