### ISSUE TITLE
notes open in All iCloud folder in Mac OS Ventura

### ISSUE THREAD

**Issue by Chris-McElroy** [sballin/alfred-search-notes-app#64]
**To Reproduce**

1. Use search notes to open a note that’s stored in a folder in iCloud
2. Note opens in All iCloud folder instead of the specific folder it’s in

I’m not sure that this is a bug but it does seem to be a functionality change since I updated to Mac OS Ventura.
I much prefer to open note within the folder that it’s stored in, if that’s possible to achieve.

**Info**

Fill out this information if it's not already included in the error text.

 - macOS version: Ventura 13.0.1 (22A400)
 - CPU: Apple M1 Pro
 - Alfred version: 5.0.5 [2096]
 - Workflow version: v3.5.2
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events? yes
 - What type of account are your notes stored in (iCloud/On My Mac/Email)? iCloud
 - If the workflow can't manage to show a list of your notes, verify that the search_notes executable file is present by right-clicking the "Search Notes" workflow in the workflow list of Alfred Preferences, choosing "Open in Finder" and opening the search_notes folder. Is there a file of the same name inside that folder? N/A
 - If no error notification appears automatically, what is the output of the [debug log](https://www.alfredapp.com/help/workflows/advanced/debugger/) when you reproduce the problem? (attached)
[notes debugger output.txt](https://github.com/sballin/alfred-search-notes-app/files/10003129/notes.debugger.output.txt)

**Comment by sballin** [comment]
Great suggestion, I've added this feature in the latest version (it can also be disabled via the environment variables): https://github.com/sballin/alfred-search-notes-app/releases/download/3.6/Search.Notes.alfredworkflow

**Comment by Chris-McElroy** [comment]
thanks!
