### ISSUE TITLE
Create Note Error

### ISSUE THREAD

**Issue by AinslieSimons** [sballin/alfred-search-notes-app#65]
Hi, 

I am getting the following error when I try to create a note via the 'nc notetext' command:

`-1719: System Events got an error: Can’t get splitter group 1 of splitter group 1 of window 1 of process "Notes". Invalid index.`

macOS Ventura 13.1
Alfred  5.0.6
python  3.9.10

any ideas?

Thanks

**Comment by nvxvi** [comment]
I also have this issue

**Comment by sballin** [comment]
Should be fixed in the latest version: https://github.com/sballin/alfred-search-notes-app/releases/download/3.6/Search.Notes.alfredworkflow
