### ISSUE TITLE
A bug occurs when creating a note

### ISSUE THREAD

**Issue by HGHEW1769** [sballin/alfred-search-notes-app#66]
Every time you create a note, the following content window pops up, and you have to close it every time, which is very unpleasant, 
hope to give support to the solution asap，thank you. 

---------------------QUOTE  -----------------
Create Note Error
-1719:“System Events”遇到一个错误：不
能获得"splitter group 1 of splitter group 1
of window 1 of process "Notes"” 。
，无效的索引
----------------UNQUOTE - ------------------

**Comment by sballin** [comment]
https://www.alfredforum.com/topic/11716-search-appleicloud-notes/?do=findComment&comment=102128

Will fix in the next version.

**Comment by JosephNajjar** [comment]
Do you know when the next version will release? Thanks for letting us all know

**Comment by sballin** [comment]
Sorry for the delay, this should be fixed in the latest version: https://github.com/sballin/alfred-search-notes-app/releases/download/3.6/Search.Notes.alfredworkflow
