### ISSUE TITLE
Shift previews not showing

### ISSUE THREAD

**Issue by PTBurnem** [sballin/alfred-search-notes-app#70]
When I use YV Suggest to search a phrase it shows results, but the previews only show for a split second and then disappear, leaving a blank, white preview pane. 

<img width="1078" alt="Screenshot 2023-10-05 at 8 41 37 AM" src="https://github.com/sballin/alfred-search-notes-app/assets/147068978/199c7a2b-1d84-4385-9a41-6c81d0abb5b0">

**Comment by sballin** [comment]
This has been requested before but unfortunately note previews are not straightforward to implement: https://github.com/sballin/alfred-search-notes-app/issues/18
