### ISSUE TITLE
Cannot look for a specific note if Notes app already open - ERROR line 2: /usr/bin/python2: No such file or directory

### ISSUE THREAD

**Issue by aleksfadini** [sballin/alfred-search-notes-app#71]
**To Reproduce**

0. Open Notes app
1. Search for a specific note (n...)
2. The note will not open, instead you will keep seeing your last selected note

Curiously enough, by quitting the Notes app, and searching for a note, the specific note searched will be opened successfully! This only started to happen after my last Alfred update.

**Error text**
From debugging:

[11:36:53.150] ERROR: Search Notes[Run Script] /Users/aleks/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/55A03AA1-5591-4D62-B1DC-7E7A0EE5D9A0: line 2: /usr/bin/python2: No such file or directory

**Info**

Fill out this information if it's not already included in the error text.

 - macOS version: Ventura 13.5.2
 - CPU: M2 Max
 - Alfred version: Latest, 5.1.4
 - Workflow version: 3.5.2
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events?
 YES

 - What type of account are your notes stored in (iCloud/On My Mac/Email)? iCloud

 - If the workflow can't manage to show a list of your notes, verify that the search_notes executable file is present by right-clicking the "Search Notes" workflow in the workflow list of Alfred Preferences, choosing "Open in Finder" and opening the search_notes folder. Is there a file of the same name inside that folder? 
 - YES
 - If no error notification appears automatically, what is the output of the [debug log]
 
[11:36:53.150] ERROR: Search Notes[Run Script] /Users/aleks/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/55A03AA1-5591-4D62-B1DC-7E7A0EE5D9A0: line 2: /usr/bin/python2: No such file or directory

ADDED NOTES:
This workflow is one of the most useful workflows I have and use. It is amazing and I am very thankful for it. Thank you for working on this!

**Comment by aleksfadini** [comment]
SOLVED: error in my system

**Comment by sballin** [comment]
Should be fixed in the latest version: https://github.com/sballin/alfred-search-notes-app/releases/download/3.6/Search.Notes.alfredworkflow
