### ISSUE TITLE
Can't search notes after reinstalling OS (21 November 2023)

### ISSUE THREAD

**Issue by jenbenn11** [sballin/alfred-search-notes-app#72]
**To Reproduce**

Steps/context to reproduce the behavior:

1. Search for a note
2. ...

**Error text**

panic: unable to open database file: operation not permitted

goroutine 1 [running]:
main.PanicOnErr(...)
github.com/sballin/alfred-search-notes-app/main.go:461
main.main()
github.com/sballin/alfred-search-notes-app/main.go:474 +0x7f3

macOS: 14.1.1
Alfred: 5.1.4
Workflow: 3.5.2
CPU: x86_64h
Binary xattrs: 
Notes DB xattrs: 
Binary info: 0755 501/jenbenn 20/staff
Notes DB info: 0644 501/jenbenn 20/staff
Query: title ''
Accounts: iCloud
**Info**

Fill out this information if it's not already included in the error text.

 - macOS version: Sonoma
 - CPU: Intel or Apple (M1)? Intel
 - Alfred version: 5
 - Workflow version: latest
 - In System Preferences > Security & Privacy > Privacy, there are checkmarks for Accessibility > Alfred 4, Full Disk Access > Alfred 4, Automation > Alfred 4 > Notes, and Automation > Alfred 4 > System Events?
 - What type of account are your notes stored in (iCloud/On My Mac/Email)?
 - If the workflow can't manage to show a list of your notes, verify that the search_notes executable file is present by right-clicking the "Search Notes" workflow in the workflow list of Alfred Preferences, choosing "Open in Finder" and opening the search_notes folder. Is there a file of the same name inside that folder?
 - If no error notification appears automatically, what is the output of the [debug log](https://www.alfredapp.com/help/workflows/advanced/debugger/) when you reproduce the problem?

**Comment by sballin** [comment]
You may need to disable/re-enable full disk access for Alfred: https://github.com/sballin/alfred-search-notes-app#required-permissions (worked in this thread: https://github.com/sballin/alfred-search-notes-app/issues/68#issuecomment-1486501128)
