### ISSUE TITLE
panic: unable to open database file: operation not permitted

### ISSUE THREAD

**Issue by dhammavipassi** [sballin/alfred-search-notes-app#77]
goroutine 1 [running]:
main.PanicOnErr(...)
github.com/sballin/alfred-search-notes-app/main.go:475
main.main()
github.com/sballin/alfred-search-notes-app/main.go:488 +0x55c

macOS: 14.4
Alfred: 5.5
Workflow: 3.6.2
CPU: arm64e
Binary xattrs: com.apple.provenance
Notes DB xattrs: 
Binary info: 0755 501/dhammavipassi 20/staff
Notes DB info: 0644 501/dhammavipassi 20/staff
Query: title ''
Accounts: iCloud

**Comment by sballin** [comment]
did you disable and re-enable permissions? https://github.com/sballin/alfred-search-notes-app?tab=readme-ov-file#troubleshooting

did you permit the binary to run? https://github.com/sballin/alfred-search-notes-app?tab=readme-ov-file#required-setup

**Comment by sballin** [comment]
Closing, feel free to reopen if these do not fix your issue.
