### ISSUE TITLE
I Press "n" and this happens. 

### ISSUE THREAD

**Issue by zyzzma** [sballin/alfred-search-notes-app#86]
**To Reproduce**

Steps/context to reproduce the behavior:

1. I Press "n" and this happens.

**Error text**

/Users/sergiopetisca/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/B9F2CB3E-929C-4390-9D20-D5DC6F8300E7: line 8: /Users/sergiopetisca/SynologyDrive/Backups/Configs/alfred congigg/Alfred.alfredpreferences/workflows/user.workflow.B5317C76-F5B4-4603-A461-93F660BA129C/search_notes/search_notes: Permission denied

macOS: 15.1
Alfred: 5.5.1
Workflow: 3.6.2
CPU: arm64e
Binary xattrs: 
Notes DB xattrs: com.apple.lastuseddate#PS
com.apple.quarantine
Binary info: 0644 501/sergiopetisca 20/staff
Notes DB info: 0644 501/sergiopetisca 20/staff
Query: title ''
Accounts: iCloud, On My Mac
**Info**

No problem with any other workflow

**Comment by zyzzma** [comment]
This is what I get after that command:
No such xattr: com.apple.quarantine

**Comment by zyzzma** [comment]
I got it to work, it was a typo on my end. Still the same though. The command goes through but the error is the exact same :/

**Comment by sballin** [comment]
Noice!
